### ISSUE TITLE
Attach Spans to LogicalPlan/Expression nodes to show the exact source code range

### ISSUE THREAD

**Issue by xerial** [wvlet/wvlet#182]
- [x] Use non-optional NodeLocation #278 
- [x] Replace NodeLocation to point NodeSpan #279 
- [x] When building parse trees, compute span range #281

**Comment by xerial** [comment]
done
