### ISSUE TITLE
Web Online Editor

### ISSUE THREAD

**Issue by xerial** [wvlet/wvlet#332]
## Goal 
Follow up #81 and make the web editor usable for managing models in local/GitHub folders

## Development items
- #473 
- [x] Remove ScalablyTyped plugin, as it can't import duckdb-wasm and generating Scala.js facade time-consuming. Rather using TypeScript directly is much easier thanks to Vite.
- [x] Merge code base with wvlet-ui-playground
- Editor
  - [ ] Localized code completion for column names and function names
  - [x] Report syntax error location #362 
  - [ ] Auto-indentation inside model blocks: model xxx = ... end and change the brackets color
  - Auto-completion
    - [ ] Fix completion when typing column or function names
  - [x] Command palette for choosing a command to run 
  - [x] Button for adding a new .wv file #376 
  - [ ] **Save and load .wv files** 
  - [x] **File explorer and file navigation shortcut**
     - local folders #341 
     - load .wv file #343 
  - [ ] Load remote projects on GitHub
  - [x] Select a profile to use #346 
  - https://github.com/wvlet/wvlet/issues/316
  - [ ] Switch profile/catalog/schema
  - [ ] Cancel query execution
  - [ ] Report errors when the server is unavailable
  - [ ] Support resizing editor/preview
  - [ ] Support tabs 
- Server
  - [x] ❗ Choose a query or subquery to run from the cursor position (i.e., Find an appropriate LogicalPlan to execute) #365 
  - [ ] Query result pagination 
  - [ ] Logging executed queries in queryable formats
  - [ ] Profile/Catalog/Schema search
  - [x] Fix loading catalogs in Trino connection #375 
  - [ ] Cleanup finished queries after a while (e.g., 30 minutes)
  - [ ] Limit debug run result size to 40 (default)
- Terminal
  - [ ] Support running a specific model or command in the terminal
  - [ ] More coloring for log terminal/preview
- Preview
  - [ ] Clip query result
  - [x] __Fix incomplete result read bug__ #350 
  - [ ] Retain preview logs upto some limit
  - [x] bug: Production run doesn't show preview
  - [ ] render charts (like Azure Data Explorer) https://learn.microsoft.com/en-us/kusto/query/render-operator?view=azure-data-explorer
- Copilot: LLM integration for code completion

## Related
- https://github.com/Azure/monaco-kusto

**Comment by Matts966** [comment]
Can we add catalog support like searching and setting schema?
Completion can be improved based on the schema & table.

**Comment by xerial** [comment]
The core features of Web UI are already implemented. The remaining tasks are more about the enhancement of the feature, so moving this item to P3

**Comment by xerial** [comment]
The motivation for editing querise online has not been so high now that we can use AI tools, local IDEs, etc. Deprioritizing this effort.
