### ISSUE TITLE
brew install script

### ISSUE THREAD

**Issue by xerial** [wvlet/wvlet#37]
- [x] Need a new release version #170 
- [x] Upload wvlet-cli-(version).tgz package to github release when a new tag is added: https://cli.github.com/manual/gh_release_upload  #172 
- [x] Prepare github.com/wvlet/homebrew-wvlet repository https://docs.brew.sh/Taps -> wvlet/homebrew-wvlet repository https://github.com/wvlet/homebrew-wvlet/tree/main 
   - [x] Confirm `brew install wvlet/wvlet/wvlet` behavior
- [x] Trigger to update homebrew-wvlet formula with a new release, using sha256 of .tgz archive -> Once updating VERSION file, a new formura file will be generated
- [x] Update installation doc 
- [x] ~Rename~ wv to wvlet for uniqueness and consistency? => Just added both wvlet and wv launch scripts #172
