### ISSUE TITLE
Scala Native Support

### ISSUE THREAD

**Issue by xerial** [wvlet/wvlet#447]
- [x] Isolate RPC interface from Scala Native or support airframe-http in Scala Native https://github.com/wvlet/airframe/pull/3724
- [x] Build lang project with Scala Native #448 
- [x] Skip ParquetAnalyzer
- [x] Support IO.readAsString(URL or path) for reading .json/.wv files #452 
- [x] Remove LogRotationHandler usage  #449 
- [x] Do not depend on ReflectTypeUtil in LogicalPlan/Expression copyInstance(..) method #450
- [x] Run unit tests
- [x] #457
- [x] Command-line compiler interface (main method) to generate SQL without accessing DBMS (offline) #454 
- [x] Support -w (workDir), -t (target), and option to read wvlet query from stdin #460

# Future Work
- [ ] #471
  - 2024-11-15: Building wvc native executable for Linux Arm (using Surface X, Windows + WSL2), Linux x64 (GitHub Action Instance), Mac Apple Silicon (my local machine) worked. Need to automate it in CI. 
   - Approach 1 (Using different os on GitHub Actions): e.g., https://github.com/indoorvivants/scala-native-binary-template 
     - [ ] Arm build is not yet supported in GitHub Actions
     - [ ] Need to manage running sbt/LLVM on Windows on GitHub Actions
     - [ ] We need to sign and synchronize binaries for Mac. Build worked
   - Approach 2: use withTargetTriple(...)
     - [ ] Need to include necessary header files for cross-build
- [x] #474
   - This will be addressed when designing #36

**Comment by xerial** [comment]
Wvlet now works as a native executable! 
```
./wvlet-native-cli/target/scala-3.3.4/wvlet-native-cli -c "select 1"
-- wvlet version=2024.9.12+8-ad94add6+20241113-1818, src=01JCM9FE9F4Y83ZDNCSD0PKG9K.wv:1
select 1
```

**Comment by xerial** [comment]
Building wvc native executable for Linux Arm (using Surface X, Windows + WSL2), Linux x64 (GitHub Action Instance), Mac Apple Silicon (my local machine) worked. Need to automate it in CI.

**Comment by xerial** [comment]
Cross compilation for building language binding will be addressed in #36
