### ISSUE TITLE
SQL to Wvlet Converter

### ISSUE THREAD

**Issue by xerial** [wvlet/wvlet#527]
As an SQL user, I would like to convert my own SQL queries into Wvlet

- [x] SQL Token/Scanner/Parser #674 
- [x] Support TPC-H #678, 
- [x] Support TPC-DS #679
- [x] Convert from LogicalPlan to Wvlet 
- [x] SQL -> LogicalPlan -> Wvlet
   - [x] Manage single/double/triple quote string literals #723 
- [ ] SQL LogicalPlan compaction rules
   - select -> column-level operators
   - function wraps -> function chain
- [ ] Add flow-style score to LogicalPlan

**Comment by xerial** [comment]
WvletGeneartor has been added in 2025.1.1. Syntax optimization will be addressed elsewhere.
